version: '3.9'

services:
  backend:
    build: ./backend          # Dockerfile - Dev Backend
    ports:
      - "${BACKEND_PORT}:3000"  # Puerto del backend mapeado con variable
    depends_on:
      - db
    env_file:
      - .env                    # Lee variables de backend si hace falta  

  frontend:
    build: ./frontend         # Dockerfile - Dev Frontend
    ports:
<<<<<<< Updated upstream
      - "8081:8081"   # debe coincidir con el puerto del contenedor
=======
      - "${FRONTEND_PORT}:8081"   # Puerto del frontend mapeado con variable
>>>>>>> Stashed changes
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
