version: '3.9'

services:
  backend:
    build: ./backend          # Dockerfile - Dev Backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend         # Dockerfile - Dev Frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: pocketcloset_db
      MYSQL_USER: pocket_user
      MYSQL_PASSWORD: pocket_pass123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
