CREATE TABLE IF NOT EXISTS users (
    id CHAR(36) NOT NULL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    idioma VARCHAR(5) DEFAULT 'es',
    avatar_url VARCHAR(255) DEFAULT NULL,
    pais VARCHAR(50) DEFAULT NULL,
    fecha INT DEFAULT NULL,
    gender VARCHAR(20) DEFAULT NULL,
    social_provider VARCHAR(50) DEFAULT NULL,
    ultimo_login TIMESTAMP DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
